#!/bin/bash
# agent-mac-ops setup.
#   ./setup.sh          interactive: write config.env, render templates
#   ./setup.sh remote   push the rendered dev-session.sh to the remote
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"

render() {
  sed -e "s|@@ALIAS_NAME@@|${ALIAS_NAME}|g" \
      -e "s|@@REMOTE_HOST@@|${REMOTE_HOST}|g" \
      -e "s|@@REMOTE_HOSTNAME@@|${REMOTE_HOSTNAME}|g" \
      -e "s|@@TMUX_SESSION@@|${TMUX_SESSION}|g" \
      -e "s|@@WORK_DIR@@|${WORK_DIR}|g" \
      "$1"
}

cmd="${1:-init}"
case "$cmd" in
  init)
    if [ -f "$ROOT/config.env" ]; then . "$ROOT/config.env"; else . "$ROOT/config.env.example"; fi
    ask() { local p="$1" d="$2" v; read -r -p "$p [$d]: " v; printf '%s' "${v:-$d}"; }

    echo "agent-mac-ops setup — answers land in config.env (gitignored)."
    echo
    REMOTE_HOST="$(ask 'SSH host/alias for your always-on Mac' "$REMOTE_HOST")"
    REMOTE_HOSTNAME="$(ask 'Remote short hostname (hostname -s on the remote)' "$REMOTE_HOSTNAME")"
    WORK_DIR="$(ask 'Dev session dir on remote (~ = home, or absolute)' "$WORK_DIR")"
    TMUX_SESSION="$(ask 'tmux session name' "$TMUX_SESSION")"
    ALIAS_NAME="$(ask 'local shell command to connect' "$ALIAS_NAME")"
    PROFILE_NAME="$(ask 'iTerm2 profile name (see SETUP.md)' "$PROFILE_NAME")"
    NOTIFY_WEBHOOK="$(ask 'notify webhook URL (blank = log-only)' "${NOTIFY_WEBHOOK:-}")"
    NOTIFY_KEY="$(ask 'webhook json key (slack/mattermost=text, discord=content)' "${NOTIFY_KEY:-text}")"
    EXTRA_LOG="$(ask 'extra remote log to surface in logs.sh (blank = none)' "${EXTRA_LOG:-}")"

    cat > "$ROOT/config.env" <<EOF
# agent-mac-ops config — generated by setup.sh. Gitignored. Edit + re-run ./setup.sh.
REMOTE_HOST="$REMOTE_HOST"
REMOTE_HOSTNAME="$REMOTE_HOSTNAME"
WORK_DIR="$WORK_DIR"
TMUX_SESSION="$TMUX_SESSION"
ALIAS_NAME="$ALIAS_NAME"
PROFILE_NAME="$PROFILE_NAME"
NOTIFY_WEBHOOK="$NOTIFY_WEBHOOK"
NOTIFY_KEY="$NOTIFY_KEY"
EXTRA_LOG="$EXTRA_LOG"
CHECK_HOUR="${CHECK_HOUR:-9}"
CHECK_MIN="${CHECK_MIN:-0}"
EOF

    render "$ROOT/control/shell-snippet.sh.tmpl" > "$ROOT/control/shell-snippet.sh"
    render "$ROOT/remote/dev-session.sh.tmpl"    > "$ROOT/remote/dev-session.sh"
    chmod +x "$ROOT/remote/dev-session.sh"

    echo
    echo "✅ wrote config.env, control/shell-snippet.sh, remote/dev-session.sh"
    echo
    echo "next:"
    echo "  1) add to ~/.zshrc, BEFORE your iTerm shell-integration line:"
    echo "       source \"$ROOT/control/shell-snippet.sh\""
    echo "  2) push the dev session to the remote:   ./setup.sh remote"
    echo "  3) do the iTerm2 GUI steps in SETUP.md  (profile + Automatic Profile Switching)"
    echo "  4) optional daily digest:                control/ops/bin/install-launchd.sh"
    echo "  5) point your agent at control/ops/ and say:  \"check on $REMOTE_HOST\""
    ;;

  remote)
    [ -f "$ROOT/config.env" ] || { echo "run ./setup.sh first" >&2; exit 1; }
    . "$ROOT/config.env"
    [ -f "$ROOT/remote/dev-session.sh" ] || { echo "missing remote/dev-session.sh — run ./setup.sh" >&2; exit 1; }
    echo "pushing dev-session.sh to $REMOTE_HOST ..."
    scp "$ROOT/remote/dev-session.sh" "$REMOTE_HOST:~/dev-session.sh"
    ssh "$REMOTE_HOST" 'chmod +x ~/dev-session.sh; command -v tmux >/dev/null || echo "⚠️  tmux not on remote — install it: brew install tmux"'
    echo "✅ dev-session.sh in place on $REMOTE_HOST"
    echo
    echo "one-time remote prep (needs admin on the remote):"
    echo "  • System Settings → General → Sharing → Remote Login = ON"
    echo "  • keep it awake:  sudo pmset -a sleep 0    (laptop, also: sudo pmset -a disablesleep 1)"
    ;;

  *) echo "usage: ./setup.sh [init|remote]" >&2; exit 1 ;;
esac
