#!/bin/bash
# agent-mac-ops setup.
#   ./setup.sh          interactive: write config.env, render templates
#   ./setup.sh render   re-render templates from an existing config.env (no prompts)
#   ./setup.sh remote   push dev-session.sh (+ the `open` shim) to the remote
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"

render() {
  sed -e "s|@@ALIAS_NAME@@|${ALIAS_NAME}|g" \
      -e "s|@@REMOTE_HOST@@|${REMOTE_HOST}|g" \
      -e "s|@@REMOTE_HOSTNAME@@|${REMOTE_HOSTNAME}|g" \
      -e "s|@@TMUX_SESSION@@|${TMUX_SESSION}|g" \
      -e "s|@@WORK_DIR@@|${WORK_DIR}|g" \
      -e "s|@@ROOT@@|${ROOT}|g" \
      -e "s|@@SSH_FORWARDS@@|${SSH_FORWARDS}|g" \
      -e "s|@@HANDOFF_PORT@@|${HANDOFF_PORT}|g" \
      -e "s|@@HANDOFF_TOKEN@@|${HANDOFF_TOKEN}|g" \
      -e "s|@@GHOSTTY_REMOTE_COLOR@@|${GHOSTTY_REMOTE_COLOR:-}|g" \
      "$1"
}

# Render every template from the current config (used by both init and render).
render_all() {
  render "$ROOT/control/shell-snippet.sh.tmpl"     > "$ROOT/control/shell-snippet.sh"
  render "$ROOT/control/bin/ghostty-connect.sh.tmpl" > "$ROOT/control/bin/ghostty-connect.sh"
  render "$ROOT/remote/dev-session.sh.tmpl"        > "$ROOT/remote/dev-session.sh"
  render "$ROOT/remote/open-handoff.sh.tmpl"       > "$ROOT/remote/open-handoff.sh"
  chmod +x "$ROOT/control/bin/ghostty-connect.sh" "$ROOT/remote/dev-session.sh" "$ROOT/remote/open-handoff.sh"
}

build_forwards() {
  local f=""
  [ "${HANDOFF_ENABLED:-true}" = "true" ] && f="-R ${HANDOFF_PORT}:localhost:${HANDOFF_PORT}"
  local p; for p in ${FORWARD_PORTS:-}; do f="$f -L $p:localhost:$p"; done
  SSH_FORWARDS="$f"
}

cmd="${1:-init}"
case "$cmd" in
  init)
    if [ -f "$ROOT/config.env" ]; then . "$ROOT/config.env"; else . "$ROOT/config.env.example"; fi
    ask() { local p="$1" d="$2" v; read -r -p "$p [$d]: " v; printf '%s' "${v:-$d}"; }

    echo "agent-mac-ops setup — answers land in config.env (gitignored)."
    echo
    REMOTE_HOST="$(ask 'SSH host/alias for your always-on Mac' "$REMOTE_HOST")"
    REMOTE_HOSTNAME="$(ask 'Remote short hostname (hostname -s on the remote)' "$REMOTE_HOSTNAME")"
    WORK_DIR="$(ask 'Dev session dir on remote (~ = home, or absolute)' "$WORK_DIR")"
    TMUX_SESSION="$(ask 'tmux session name' "$TMUX_SESSION")"
    ALIAS_NAME="$(ask 'local shell command to connect' "$ALIAS_NAME")"
    PROFILE_NAME="$(ask 'iTerm2 profile name (see SETUP.md)' "$PROFILE_NAME")"
    GHOSTTY_REMOTE_COLOR="$(ask 'Ghostty remote background tint, hex (blank = no tint)' "${GHOSTTY_REMOTE_COLOR:-#2a1f3d}")"
    FORWARD_PORTS="$(ask 'ports to auto-forward on connect (space-sep, blank = none)' "${FORWARD_PORTS:-}")"
    HANDOFF_ENABLED="$(ask 'open remote auth URLs on this Mac? (true/false)' "${HANDOFF_ENABLED:-true}")"
    HANDOFF_PORT="$(ask 'handoff listener port' "${HANDOFF_PORT:-17999}")"
    NOTIFY_WEBHOOK="$(ask 'notify webhook URL (blank = log-only)' "${NOTIFY_WEBHOOK:-}")"
    NOTIFY_KEY="$(ask 'webhook json key (slack/mattermost=text, discord=content)' "${NOTIFY_KEY:-text}")"
    EXTRA_LOG="$(ask 'extra remote log to surface in logs.sh (blank = none)' "${EXTRA_LOG:-}")"

    # Generate a stable handoff token once; keep it across re-runs.
    HANDOFF_TOKEN="${HANDOFF_TOKEN:-}"
    [ -z "$HANDOFF_TOKEN" ] && HANDOFF_TOKEN="$(uuidgen 2>/dev/null || date +%s%N)"

    build_forwards

    cat > "$ROOT/config.env" <<EOF
# agent-mac-ops config — generated by setup.sh. Gitignored. Edit + re-run ./setup.sh.
REMOTE_HOST="$REMOTE_HOST"
REMOTE_HOSTNAME="$REMOTE_HOSTNAME"
WORK_DIR="$WORK_DIR"
TMUX_SESSION="$TMUX_SESSION"
ALIAS_NAME="$ALIAS_NAME"
PROFILE_NAME="$PROFILE_NAME"
GHOSTTY_REMOTE_COLOR="$GHOSTTY_REMOTE_COLOR"
FORWARD_PORTS="$FORWARD_PORTS"
HANDOFF_ENABLED="$HANDOFF_ENABLED"
HANDOFF_PORT="$HANDOFF_PORT"
HANDOFF_TOKEN="$HANDOFF_TOKEN"
NOTIFY_WEBHOOK="$NOTIFY_WEBHOOK"
NOTIFY_KEY="$NOTIFY_KEY"
EXTRA_LOG="$EXTRA_LOG"
CHECK_HOUR="${CHECK_HOUR:-9}"
CHECK_MIN="${CHECK_MIN:-0}"
EOF

    render_all

    echo
    echo "✅ wrote config.env + rendered shell-snippet.sh, ghostty-connect.sh, dev-session.sh, open-handoff.sh"
    echo
    echo "next:"
    echo "  1) add to ~/.zshrc, BEFORE your iTerm shell-integration line:"
    echo "       source \"$ROOT/control/shell-snippet.sh\""
    echo "  2) push to the remote:                   ./setup.sh remote"
    echo "  3) iTerm2 GUI steps in SETUP.md          (profile + Automatic Profile Switching)"
    echo "     Ghostty users: no GUI steps — '$ALIAS_NAME' just works (see SETUP.md §4b)."
    [ "${HANDOFF_ENABLED}" = "true" ] && \
    echo "  4) browser handoff listener:             control/bin/install-open-listener.sh"
    echo "  5) optional daily digest:                control/ops/bin/install-launchd.sh"
    echo "  6) point your agent at control/ops/ and say:  \"check on $REMOTE_HOST\""
    ;;

  render)
    [ -f "$ROOT/config.env" ] || { echo "no config.env — run ./setup.sh first" >&2; exit 1; }
    . "$ROOT/config.env"
    build_forwards
    render_all
    echo "✅ re-rendered shell-snippet.sh, ghostty-connect.sh, dev-session.sh, open-handoff.sh from config.env"
    ;;

  remote)
    [ -f "$ROOT/config.env" ] || { echo "run ./setup.sh first" >&2; exit 1; }
    . "$ROOT/config.env"
    [ -f "$ROOT/remote/dev-session.sh" ] || { echo "missing remote/dev-session.sh — run ./setup.sh" >&2; exit 1; }
    echo "pushing to $REMOTE_HOST ..."
    scp "$ROOT/remote/dev-session.sh" "$REMOTE_HOST:~/dev-session.sh"
    ssh "$REMOTE_HOST" 'chmod +x ~/dev-session.sh; command -v tmux >/dev/null || echo "⚠️  tmux not on remote — install it: brew install tmux"'

    # Install Ghostty's terminfo on the remote so TERM=xterm-ghostty resolves there.
    # Without it, native Ghostty sessions send an unknown TERM and keystrokes come
    # back garbled/doubled. Ghostty ships its terminfo INSIDE the app bundle, not the
    # system db — so look there too. dev-session.sh also falls back to xterm-256color,
    # so this is fidelity, not a hard requirement (best-effort, safe under set -e).
    GTI=""
    if ! infocmp -x xterm-ghostty >/dev/null 2>&1; then
      for d in /Applications/Ghostty.app "$HOME/Applications/Ghostty.app"; do
        if TERMINFO="$d/Contents/Resources/terminfo" infocmp -x xterm-ghostty >/dev/null 2>&1; then
          GTI="$d/Contents/Resources/terminfo"; break
        fi
      done
      HAVE_GTI=$([ -n "$GTI" ] && echo 1 || echo "")
    else
      HAVE_GTI=1
    fi
    if [ -n "${HAVE_GTI:-}" ]; then
      if { [ -n "$GTI" ] && env TERMINFO="$GTI" infocmp -x xterm-ghostty || infocmp -x xterm-ghostty; } 2>/dev/null \
           | ssh "$REMOTE_HOST" 'tic -x - >/dev/null 2>&1'; then
        echo "✅ installed xterm-ghostty terminfo on $REMOTE_HOST"
      else
        echo "⚠️  couldn't install xterm-ghostty terminfo (sessions fall back to xterm-256color — fine)"
      fi
    else
      echo "ℹ️  no local xterm-ghostty terminfo found — Ghostty sessions use xterm-256color (fine)"
    fi
    if [ "${HANDOFF_ENABLED:-true}" = "true" ] && [ -f "$ROOT/remote/open-handoff.sh" ]; then
      ssh "$REMOTE_HOST" 'mkdir -p ~/bin'
      scp "$ROOT/remote/open-handoff.sh" "$REMOTE_HOST:~/bin/open"
      ssh "$REMOTE_HOST" 'chmod +x ~/bin/open'
      echo "✅ pushed dev-session.sh + ~/bin/open (browser handoff shim)"
    else
      echo "✅ pushed dev-session.sh (handoff disabled — no shim)"
    fi
    echo
    echo "one-time remote prep (needs admin on the remote):"
    echo "  • System Settings → General → Sharing → Remote Login = ON"
    echo "  • keep it awake:  sudo pmset -a sleep 0    (laptop, also: sudo pmset -a disablesleep 1)"
    ;;

  *) echo "usage: ./setup.sh [init|render|remote]" >&2; exit 1 ;;
esac
